# Generated by Django 6.0.6 on 2026-06-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceControlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=50, verbose_name='属性名称')),
                ('old_value', models.CharField(max_length=20, verbose_name='原值')),
                ('new_value', models.CharField(max_length=20, verbose_name='新值')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('message', models.CharField(blank=True, max_length=200, verbose_name='返回信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='控制时间')),
            ],
            options={
                'verbose_name': '控制日志',
                'verbose_name_plural': '控制日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(default=0, verbose_name='温度(°C)')),
                ('light', models.IntegerField(default=0, verbose_name='光照(Lux)')),
                ('fan_speed', models.IntegerField(default=0, verbose_name='风扇转速(r/min)')),
                ('curtain_step', models.IntegerField(default=0, verbose_name='窗帘位置(步)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '传感器数据',
                'verbose_name_plural': '传感器数据',
                'ordering': ['-created_at'],
            },
        ),
    ]
