# Generated by Django 6.0.6 on 2026-06-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='curtain_step',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='alarm',
            field=models.IntegerField(default=0, verbose_name='警报器(0=关/1=开)'),
        ),
    ]
