# Generated by Django 6.0.6 on 2026-06-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_sensordata_curtain_step_sensordata_alarm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='alarm',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='led',
            field=models.IntegerField(default=0, verbose_name='LED(0=灭/1=亮)'),
        ),
    ]
